# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="fino"
#ZSH_THEME="cobalt2"
ZSH_THEME="honukai"

# Example aliases
alias zshconfig="subl ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"
alias git='hub'
alias g='git'
alias tf='terraform'

#
#
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ssh-agent brew brew-cask catimg git git-extras github osx sublime vagrant z zsh-syntax-highlighting history history-substring-search)

source $ZSH/oh-my-zsh.sh

# ZSH History Search Bindings
##Vi
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

##Emacs
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down


# User configuration

#Highlight any time you type rm -rf in red
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')

#Add a 10 second wait before you can confirm a wildcard deletion
setopt RM_STAR_WAIT

export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";


export PATH="/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/opt/go/libexec/bin:/Users/lpm/bin"

# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#source ~/.bin/tmuxinator.zsh
export EDITOR='vim'

#man() {
# Original from http://boredzo.org/blog/archives/2016-08-15/colorized-man-pages-understood-and-customized
#        env \
#            LESS_TERMCAP_mb=$(printf "\e[1;31m") \
#            LESS_TERMCAP_md=$(printf "\e[1;31m") \
#            LESS_TERMCAP_me=$(printf "\e[0m") \
#            LESS_TERMCAP_se=$(printf "\e[0m") \
#            LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
#            LESS_TERMCAP_ue=$(printf "\e[0m") \
#            LESS_TERMCAP_us=$(printf "\e[1;32m") \
#            man "$@"
#}

man() {
        env \
             LESS_TERMCAP_mb=$'\e[1;31m' \
             LESS_TERMCAP_md=$'\e[1;36m' \
             LESS_TERMCAP_me=$'\e[0m' \
             LESS_TERMCAP_se=$'\e[0m' \
             LESS_TERMCAP_so=$'\e[1;40;92m' \
             LESS_TERMCAP_ue=$'\e[0m' \
             LESS_TERMCAP_us=$'\e[1;32m' \
             man "$@"
}
autoload bashcompinit && bashcompinit
source '/Users/lpm/lib/azure-cli/az.completion'
source /usr/local/opt/chruby/share/chruby/chruby.sh
